### ISSUE TITLE
Need to describe in more details range-bitmap leaf usage 

### ISSUE THREAD

**Issue by sergiobelotti** [tsaad-dev/te#100]
A new description  of the range-bitmap leaf in the label-restriction-info grouping has been proposed to update draft-ietf-teas-yang-te-types-13.
This is the description:
"In case the restriction is 'inclusive', the bit-position is set if the corresponding mapped label is available. In this case, if the range-bitmap is not present, all the labels in the range are available.
In case the restriction is 'exclusive', the bit-position is set if the corresponding mapped label is not available. In this case, if the range-bitmap is not present, all the labels in the range are not available."
Need to add a description of the usage of this restriction range  e.g. in OTN with time slot/tributary port  list .

**Comment by italobusi** [comment]
See: https://mailarchive.ietf.org/arch/msg/teas/WlMUpQre56VBaRc9YCF24G2c4Uw/
