### ISSUE TITLE
In leaf admin state, change identityref base from tunnel-admin-type to te-types:tunnel-admin-state-type

### ISSUE THREAD

**Issue by oscargdd** [tsaad-dev/te#101]
The Admin state types are defined in te types, they should not be redefined in te tunnel. 

Current:

leaf admin-state {
      type identityref {
        base tunnel-admin-type;
      }
 default tunnel-admin-up;
      description "TE tunnel administrative state.";
    }

Change to

leaf admin-state {
      type identityref {
        base te-types:tunnel-admin-state-type;
      }
 default te-types:tunnel-admin-state-up;
      description "TE tunnel administrative state.";
    }

**Comment by italobusi** [comment]
@oscargdd : the reason for defining a different type is because we need to support the tunnel-admin-auto status which is applicable only to te-tunnels:

https://github.com/tsaad-dev/te/blob/c04f258fe54dd9f22fec1dec4ea7a38f83abeee9/ietf-te.yang#L265-L272

**Comment by italobusi** [comment]
**2020-04-22 TEAS Call**

The te-types:tunnel-admin-state-type is not used by te-topology so it could be used here

A new identity can be defined for the tunnel-admin-auto based on te-types:tunnel-admin-state-type
