### ISSUE TITLE
Incorporate TE tunnel segments

### ISSUE THREAD

**Issue by tsaad-dev** [tsaad-dev/te#108]
Proposed change:

 ``` all TE tunnels and TE tunnel segments originating from device(s)```

```
   device.  When the model is used to manage a TE controller, the
   'tunnels' list contains all TE tunnels originating from device(s)
   that the TE controller manages.

```

My understanding is that when this model is used to manage a TE controller, the 'tunnels' list contains also the tunnel segments terminated or transiting through the domain.

_Originally posted by @italobusi in https://github.com/tsaad-dev/te/issue_comments/698934865_

**Comment by tsaad-dev** [comment]
Updated.

5.1.2.  TE Tunnels

   The set of TE tunnels are provisioned under the 'tunnels' container
   (see Figure 4).  A TE tunnel in the list is uniquely identified by a
   name.  When the model is used to manage a specific device, the
   'tunnels' list contains the TE tunnels originating from the specific
   device.  When the model is used to manage a TE controller, the
   'tunnels' list contains all TE tunnels and TE tunnel segments
   originating from device(s) that the TE controller manages.

**Comment by tsaad-dev** [comment]
When the model is used on a device, the
'tunnels' list contains the TE tunnels and TE tunnel segments present on the
device.
When the model is used on a TE controller, the
'tunnels' list contains all TE tunnels and TE tunnel segments
that the TE controller manages.

**Comment by italobusi** [comment]
Closed with https://tools.ietf.org/html/draft-ietf-teas-yang-te-26
