### ISSUE TITLE
> @italobusi : check which definition could be put in this draft (better not to define terms which are not used in the document)

### ISSUE THREAD

**Issue by tsaad-dev** [tsaad-dev/te#109]
> @italobusi : check which definition could be put in this draft (better not to define terms which are not used in the document)

What about adding the following definitions:

>    TE Tunnel: a connection-oriented service provided by a layer
>    network of delivery of a client's data between source and
>    destination tunnel termination points.
> 
>    TE Tunnel Segment: a part of a multi-domain TE tunnel that spans
>    a given network domain.
> 
>    TE Tunnel Hand-off: an access link or inter-domain link by which
>    a multi-domain TE tunnel enters or exits a given network domain.
> 

The tunnel segment definition is assumed by this piece of code:

```
    container path-in-segment {
      presence "The end-to-end tunnel starts in a previous domain;
                this tunnel is a segment in the current domain.";
      description
        "If an end-to-end tunnel crosses multiple domains using
         the same technology, some additional constraints have to be
         taken in consideration in each domain.
         This tunnel is a segment that needs to be coordinated
         with previous segment stitched on head-end side.";
      uses te-types:label-set-info;
    }
    container path-out-segment {
      presence
        "The end-to-end tunnel is not terminated in this domain;
         this tunnel is a segment in the current domain.";
      description
        "If an end-to-end tunnel crosses multiple domains using
         the same technology, some additional constraints have to be
         taken in consideration in each domain.
         This tunnel is a segment that needs to be coordinated
         with previous segment stitched on head-end side.";
      uses te-types:label-set-info;
    }

```

The tunnel hand-off definition could be used to improve the description above (the path-in-segment and path-out-segment in fact are used to configure the hand-off points)

_Originally posted by @italobusi in https://github.com/tsaad-dev/te/issue_comments/698933499_

**Comment by tsaad-dev** [comment]
Proposed text:

Headend                    UHP            BN1                                       BN2                               Tail-end
        T1. tunnel-segment              T2 tunnel-segment            T3 tunnel-segment 
                                                        Incoming label.                   Incoming Label
                                                        Acceptable                          Acceptable
                                                        Label Set                             Label Set
  


    container path-in-segment {
      presence "The end-to-end tunnel starts in a previous domain;
                this tunnel is a segment in the current domain.";
      description
        "If an end-to-end tunnel crosses multiple domains using
         the same technology, some additional constraints have to be
         taken in consideration in each domain.
         This TE tunnel segment is stitched to the upstream TE tunnel segment or the headend.";
      uses te-types:label-set-info;



    container path-out-segment {
      presence
        "The end-to-end tunnel is not terminated in this domain;
         this tunnel is a segment in the current domain.";
      description
        "If an end-to-end tunnel crosses multiple domains using
         the same technology, some additional constraints have to be
         taken in consideration in each domain.
         This TE tunnel segment is stitched to the downstream TE tunnel segment.";

**Comment by tsaad-dev** [comment]
uses te-types:label-set-info; is an optional path constraint.
This can be fed in (e.g. by Hierarchical PCE) to limit the K-paths that can be produced by domain controller.

**Comment by tsaad-dev** [comment]
This is relevant for "compute-only" tunnels.

**Comment by italobusi** [comment]
> uses te-types:label-set-info; is an optional path constraint.
> This can be fed in (e.g. by Hierarchical PCE) to limit the K-paths that can be produced by domain controller.

See also: https://github.com/tsaad-dev/te/issues/88#issuecomment-710094341

**Comment by italobusi** [comment]
**2020-10-16 TEAS call**

Proposed to update the definition:

OLD
`This TE tunnel segment is stitched to the upstream TE tunnel segment or the headend.
`
NEW
`This TE tunnel segment is stitched to the upstream TE tunnel segment.`

**Comment by italobusi** [comment]
@tsaad-dev : update the description in the YANG model:

```
container path-in-segment {
  presence "The end-to-end tunnel starts in a previous domain;
            this tunnel is a segment in the current domain.";
  description
    "If an end-to-end tunnel crosses multiple domains using
     the same technology, some additional constraints have to be
     taken in consideration in each domain.
     This TE tunnel segment is stitched to the upstream TE tunnel segment.";
  uses te-types:label-set-info;



container path-out-segment {
  presence
    "The end-to-end tunnel is not terminated in this domain;
     this tunnel is a segment in the current domain.";
  description
    "If an end-to-end tunnel crosses multiple domains using
     the same technology, some additional constraints have to be
     taken in consideration in each domain.
     This TE tunnel segment is stitched to the downstream TE tunnel segment.";

```
