### ISSUE TITLE
Clarification on the association-object

### ISSUE THREAD

**Issue by haomianzheng** [tsaad-dev/te#111]
in draft-ietf-teas-yang-te-25 we have the following pieces for association tunnel:

```
 +--rw association-objects
   +--rw association-object* [association-key]
   |  +--rw association-key    string
   |  +--rw type?              identityref
   |  +--rw id?                uint16
   |  +--rw name?              string
   |  +--rw source
   |     +--rw id?     te-generic-node-id
   |     +--rw type?   enumeration
```

However we don't have explicit interpretation about the key 'association-key'. As the 'name' is used as the key for tunnel representation, shall we put the name as the association-key? 
Or in other word, how to represent the association tunnel via the name?

**Comment by tsaad-dev** [comment]
@italobusi : please follow-up with @haomianzheng .

The problem is not clear - why name is being added?
Example: if tunnel A, tunnel B, tunnel C, etc. needs to be associated
tunnel A
  association object
     association-key=foo
     id=10

tunnel B
  association object
     association-key=foo
     id=10

tunnel C
  association object
     association-key=foo
     id=10

**Comment by haomianzheng** [comment]
> @italobusi : please follow-up with @haomianzheng .
> 
> The problem is not clear - why name is being added?
> Example: if tunnel A, tunnel B, tunnel C, etc. needs to be associated
> tunnel A
> association object
> association-key=foo
> id=10
> 
> tunnel B
> association object
> association-key=foo
> id=10
> 
> tunnel C
> association object
> association-key=foo
> id=10

The explanation here is clear, and how to allocate the ID on MPI would be implementation dependent. Issue closed.
