### ISSUE TITLE
PCE-Initiated Tunnel/LSP

### ISSUE THREAD

**Issue by dhruvdhody** [tsaad-dev/te#112]
What is the way to identify if an LSP was initiated via PCE (using PCEP) in your model? Is this something that should be added?

**Comment by tsaad-dev** [comment]
Add controller container (to be used as target for augmentation)

**Comment by dhruvdhody** [comment]
Thanks for handling this!

**Comment by italobusi** [comment]
Closed during the 2021-04-30 TEAS call
