### ISSUE TITLE
MPLS-TE label range augmentations

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#117]
Need to investigate the need to defined MPLS-TE label range augmentations

See: https://tools.ietf.org/html/draft-busizheng-teas-yang-te-mpls-topology-00

**Comment by italobusi** [comment]
**2020-12-18 TEAS Call**

MPLS-TE label ranges are usually per node and not per link (as in current TE topology model)

Also in case of abstract nodes, MPLS-TE label ranges are allocated per node:

![image](https://user-images.githubusercontent.com/12461741/103247273-9d54bc00-4966-11eb-91ab-44fa3d420cec.png)

**Comment by tsaad-dev** [comment]
MPLS label are usually node local scope.
We did not see advertising available labels per link in topology is useful.
MPLS-RIB shows the available/used labels on per node.
