### ISSUE TITLE
Renaming 'Group' in named-srlgs grouping

### ISSUE THREAD

**Issue by haomianzheng** [tsaad-dev/te#124]
In the current grouping named-srlgs, the tree structure is as follow: 

```
+--rw named-srlgs
      |  +--rw named-srlg* [name] {te-types:named-srlg-groups}?
      |     +--rw name     string
      |     +--rw group?   te-types:srlg
      |     +--rw cost?    uint32
```
where the group is described as 'an SRLG **value**'. 

```
leaf group {
          type te-types:srlg;
          description
            "An SRLG value.";
        }
```

In this way shall we rename the 'group' as 'srlg-value'? The type won't need to be changed.

**Comment by italobusi** [comment]
In a nutshell the proposal is:

c/leaf group/leaf srlg-value/

**Comment by tsaad-dev** [comment]
named value as per discussions
