### ISSUE TITLE
Common rules for TE-related YANG modules prefixes 

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#125]
We have got a YANG doctor review comment on OTN topology YANG model advocating that "modules from a common group could use some common and obvious rules for prefixes"

See mail thread in CCAMP and TEAS WGs: https://mailarchive.ietf.org/arch/msg/teas/ErIhvMZOrB6DxyQlCkGcdbMPV9w/

**Comment by italobusi** [comment]
2021-01-29 TEAS Call

| Model            | TE   | OTN   | WSON   | Flexi-Grid | Packet-TE | ETH-TE   | MPLS-TE   |
|==================|======|=======|========|============|===========|==========|===========|
| Topology         | tet  | otnt  | wsont  | flexigt    | pkt-tet   | eth-tet  | mpls-tet  |
| Tunnel           | tetn | otntn | wsontn | flexigtn   | N/A       | eth-tetn | mpls-tetn |
| Path Computation | tepc | otnpc | wsonpc | flexigpc   | N/A       | eth-tepc | mpls-tepc |

**Comment by italobusi** [comment]
After the call I  have noted that the types were missing from the table:

| Model            | TE   | OTN   | WSON   | Flexi-Grid | Packet-TE | ETH-TE   | MPLS-TE   |
|----------------|-----|--------|----------|------------|------------|-----------|------------|
| **Types**         | te-types| l1-types  | l0-types   | | te-packet-types   | eth-te-types  | mpls-te-types  |
| **Topology**         | tet  | otnt  | wsont  | flexigt    | pkt-tet   | eth-tet  | mpls-tet  |
| **Tunnel**           | tetn | otntn | wsontn | flexigtn   | N/A       | eth-tetn | mpls-tetn |
| **Path Computation** | tepc | otnpc | wsonpc | flexigpc   | N/A       | eth-tepc | mpls-tepc |

**Comment by tsaad-dev** [comment]
AI (Italo): follow up Tom on proposal.
For now, no changes needed.

ietf-l3-te-topology-state.yang
ietf-l3-te-topology.yang
      prefix "l3tet";

ietf-rsvp-te-mpls.yang
ietf-te-device.yang

ietf-te-mpls.yang
   prefix "te-mpls";
   prefix "mpls-tetnl";

ietf-te-topology.yang
   prefix "tet";


ietf-te-packet-types.yang
ietf-te-path-computation.yang
    prefix "tepc";

ietf-te-mpls-path-computation.yang
   prefix "mpls-te-pc";


ietf-te-sr-mpls.yang
ietf-te-topology-packet-state.yang
ietf-te-topology-packet.yang
ietf-te-topology-state.yang

ietf-te-types.yang

ietf-te.yang
  prefix "tetnl";

**Comment by italobusi** [comment]
This is my understanding of the table based on today's discussion:

| Model            | TE   | OTN   | WSON   | Flexi-Grid | Packet-TE | ETH-TE   | MPLS-TE   |
|----------------|-----|--------|----------|------------|------------|-----------|------------|
| **Types**         | **_te-types_**| l1-types  | l0-types   | l0-types  | **_te-packet-types_**   | eth-te-types  | mpls-te-types  |
| **Topology**         | **_tet_**  | otnt  | _wsont_  | flexigt    | pkt-tet   | eth-tet  | mpls-tet  |
| **Tunnel**           | tetnl | otntnl | wsontnl | flexigtnl   | N/A       | eth-tetnl | mpls-tetnl |
| **Path Computation** | tepc | otnpc | wsonpc | flexigpc   | N/A       | eth-tepc | mpls-tepc |

**Notes:**
- TE types and Packet-TE Type prefixes already published in RFC8776
- TE Topology prefix already published in RFC8795
- WSON Topology prefix defined in a draft which have just been approved by IESG (in RFC Queue)

**Comment by italobusi** [comment]
@tsaad-dev : update the prefix as `te-tnl` and inform the authors of the impacted model of the change

**Comment by italobusi** [comment]
**2021-11-19 TE Call**

@italobusi : raise this as a WG LC comment

**Comment by italobusi** [comment]
**2023-02-24 TE Call**

Let's keep the current prefix. It is ok if augmenting model have different prefixes.
