### ISSUE TITLE
Default value for graceful local restart timer

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#131]
https://github.com/tsaad-dev/te/blob/692d392ff805f0d05b02bbec2d49131b31ae48f6/ietf-rsvp.yang#L151-L160

There are implementations (GMPLS for Optical networks) where this timer is set to 0xFFFFFFFF (to never expire) and cannot be configured

**Comment by tsaad-dev** [comment]
to remove default since no suggested value in RFC3473
