### ISSUE TITLE
Default value for graceful local recovery timer

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#132]
https://github.com/tsaad-dev/te/blob/692d392ff805f0d05b02bbec2d49131b31ae48f6/ietf-rsvp.yang#L161-L172

There are implementations (GMPLS for Optical networks) where this timer is set to 12 hours and cannot be configured

**Comment by tsaad-dev** [comment]
to remove default since RFC3473 does not suggest a specific value.
