### ISSUE TITLE
Default values for graceful neighbor timers

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#133]
https://github.com/tsaad-dev/te/blob/692d392ff805f0d05b02bbec2d49131b31ae48f6/ietf-rsvp.yang#L173-L196

These timers are config=false: does the default value has any meaning?

See #131 and #132 for values used with some GMPLS implementations for optical networks

**Comment by italobusi** [comment]
The description added in https://datatracker.ietf.org/doc/html/draft-ietf-teas-yang-rsvp-17 about the 0xffffffff is good

However, the issue still applies: since these timers are config=false, does the default value has any meaning?

**Comment by tsaad-dev** [comment]
remove          defaults since both timers are RO
