### ISSUE TITLE
Graceful restart helper mode

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#134]
https://github.com/tsaad-dev/te/blob/692d392ff805f0d05b02bbec2d49131b31ae48f6/ietf-rsvp.yang#L197-L205

I have not yet found any information about it

Is it mandatory to be implemented, especially in GMPLS for optical networks?

I cannot find any definition of helper mode in RFC 5063

**Comment by italobusi** [comment]
The description added in https://datatracker.ietf.org/doc/html/draft-ietf-teas-yang-rsvp-17 clarifies the definition:

```
         container helper-mode {
           description
             "Helper mode information. In this mode, the node
              resynchronize its stored states with a neighbor whose
              control plane has restarted. The helper mode term is
              borrowed from RFC3623 and adopted by several vendors
              vendors in their implementation of RSVP graceful restart.";
           leaf enabled {
             type boolean;
             default "true";
             description
               "'true' if helper mode is enabled.";
           }      
```

However, I think the default statement would better be removed

It seems that this is a non standardized feature which, even if implemented by several vendors, is not mandatory to be implemented

Defining the default value as true would cause issues in cases the feature is not implemented (a deviation statement has to be defined)

Is there any technical issue if some implementations enable this feature by default while other implementations disable this feature by default?

**Comment by tsaad-dev** [comment]
remove default = true from
           leaf enabled {
             type boolean;
             description
               "'true' if helper mode is enabled.";
           }
