### ISSUE TITLE
Default value for authentication key

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#135]
https://github.com/tsaad-dev/te/blob/692d392ff805f0d05b02bbec2d49131b31ae48f6/ietf-rsvp.yang#L278-L285

There are implementations that do not have a default value for the authentication key: does it make sense to define a default value for authentication key?

IMHO, the authentication key MUST be provided when authentication is enabled like the crypto algorithm.

Moreover, I am not sure this attribute is applicable when authentication is disabled: see also #136 

Proposed code change:

```
 leaf authentication-key { 
   when ../enabled;
   type string;
   mandatory true;
   description 
     "An authentication key string."; 
   reference 
     "RFC2747: RSVP Cryptographic Authentication"; 
 } 

```

**Comment by tsaad-dev** [comment]
leaf authentication-key { 
   type string;
   description 
     "An authentication key string."; 
   reference 
     "RFC2747: RSVP Cryptographic Authentication"; 
 }

**Comment by tsaad-dev** [comment]
as per plan of record remove the default.
