### ISSUE TITLE
When statement for crypto algorithm

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#136]
https://github.com/tsaad-dev/te/blob/692d392ff805f0d05b02bbec2d49131b31ae48f6/ietf-rsvp.yang#L286-L293

This code requires the client to configure the crypto algorithm also when authentication is disabled

Proposed change:

```
      leaf crypto-algorithm {
        when ../enabled;
        type identityref {
          base key-chain:crypto-algorithm;
        }
        mandatory true;
        description
          "Cryptographic algorithm associated with key.";
      }

```

**Comment by tsaad-dev** [comment]
leaf crypto-algorithm {
        type identityref {
          base key-chain:crypto-algorithm;
        }
        description
          "Cryptographic algorithm associated with key.";
      }

**Comment by tsaad-dev** [comment]
To remove mandatory and leave it to vendor to choose a default.
