### ISSUE TITLE
Default value for session name

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#137]
https://github.com/tsaad-dev/te/blob/692d392ff805f0d05b02bbec2d49131b31ae48f6/ietf-rsvp.yang#L348-L353

I am not sure the empty string is a valid/useable default value

Should the session name be mandatory=true instead?

Please also note that the session-attributes grouping is used only once as config=false. If it is not intended to be re-used with config=true, has this default value any meaning?

**Comment by tsaad-dev** [comment]
remove default "";  to allow
- missing name (i.e. null)
- empty if it comes "" in signaling
- valid non-null string

**Comment by tsaad-dev** [comment]
remove default.
