### ISSUE TITLE
Default value for session status

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#138]
https://github.com/tsaad-dev/te/blob/692d392ff805f0d05b02bbec2d49131b31ae48f6/ietf-rsvp.yang#L354-L368

I think the session status should be config=false. Therefore, has this default value any meaning?

Please also note that the session-attributes grouping is used only once as config=false.

If it is intended to be re-used with config=true, then this leaf should be marked as config=false.

**Comment by tsaad-dev** [comment]
remove "default "down";" since it is RO.

**Comment by tsaad-dev** [comment]
consider whether the grouping is RO always and put config=false in that case.
