### ISSUE TITLE
Default value for reservation style

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#140]
https://github.com/tsaad-dev/te/blob/692d392ff805f0d05b02bbec2d49131b31ae48f6/ietf-rsvp.yang#L412-L419

There are implementations (GMPLS for Optical networks) where the reservation style is set to FF by default and cannot be configured: in this case there is no need for the mandatory=true statement

Moreover, the rsb list can only be used with config=false because it does not have a key: does this default value has any meaning?

Please also note that the session-attributes grouping is used only once as config=false. If it is intended to be re-used with config=true, the rsb list should be marked as config=false.

**Comment by tsaad-dev** [comment]
to remove "mandatory "true";  since it is RO.
