### ISSUE TITLE
Default values for extended graceful restart timers

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#143]
https://github.com/tsaad-dev/te/blob/692d392ff805f0d05b02bbec2d49131b31ae48f6/ietf-rsvp-extended.yang#L80-L101

I have not yet found any information about it

What is the difference between the extended restart and recovery timer and the local restart and recovery timer in the graceful-restart grouping?

**Comment by italobusi** [comment]
In https://datatracker.ietf.org/doc/html/draft-ietf-teas-yang-rsvp-17 all the attributes within the grouping has been removed

Shall the grouping and its usage be removed from he model completely?

**Comment by tsaad-dev** [comment]
the grouping contents was removed from rsvp extended and hence I deleted it.
