### ISSUE TITLE
Default values for extended authentication

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#144]
https://github.com/tsaad-dev/te/blob/692d392ff805f0d05b02bbec2d49131b31ae48f6/ietf-rsvp-extended.yang#L103-L152

I have not yet found any information about it

Is it mandatory to implement this grouping, in particular in GMPS for optical networks?

**Comment by tsaad-dev** [comment]
remove defaults - and allow implementation to set their own.
