### ISSUE TITLE
Switching type in ietf-te examples

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#174]
In the ietf-te examples only the `encoding `is specified while the `switching-type` is omitted

For example in section 13.1:

```
   {
     "ietf-te:tunnel": [
       {
         "name": "Example_LSP_Tunnel_A_2",
         "encoding": "te-types:lsp-encoding-packet",
         "admin-state": "te-types:tunnel-state-up",
         "source": "10.0.0.1",
         "destination": "10.0.0.4",
         "bidirectional": "false",
         "signaling-type": "te-types:path-setup-rsvp"
       }
     ]
   }

```

Is there a reason why the the `switching-type` is omitted?

Co-Authored-By: sergio belotti <sergio.belotti@nokia.com>

**Comment by oscargdd** [comment]
I made the example for MPLS networks. In that case enconding is enough. For GMPLS networks (OTN/WDM) we require the switching type.

**Comment by italobusi** [comment]
> I made the example for MPLS networks. In that case enconding is enough. For GMPLS networks (OTN/WDM) we require the switching type.

Thanks for the explanation: now it is clear to me

Maybe adding some note in the appendix would make this assumption more explicit also to other readers

**Comment by tsaad-dev** [comment]
Added note to clarify in draft.

**Comment by italobusi** [comment]
Closed in [draft-ietf-teas-yang-te-29](https://datatracker.ietf.org/doc/html/draft-ietf-teas-yang-te-29)
