### ISSUE TITLE
Neighbor expiry time

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#179]
https://github.com/tsaad-dev/te/blob/692d392ff805f0d05b02bbec2d49131b31ae48f6/ietf-rsvp.yang#L446-L453

As discussed in #139, there are implementations (GMPLS for Optical networks) where this timer is set to 0xFFFFFFFF (to never expire)

Moreover, does it make sense to define a default for the configuration of the neighbor node which may have a different defatul value than the local node?

I think that if the value is not configured it would mean that the expiry time used by the neighbor is not known but may be learnt by the device and eventually reported in the operational datastore.

It is proposed to remove the default value.

**Comment by tsaad-dev** [comment]
To update whether 180 sec default can be removed altogether.

**Comment by tsaad-dev** [comment]
Converged to remove the default for this leaf as we know of no standard value for it.
