### ISSUE TITLE
Preference for secondary reverse paths

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#192]
In https://datatracker.ietf.org/doc/html/draft-ietf-teas-yang-te-29, preference was defined for primary, secondary and reverse secondary paths (using the preference grouping)

In https://datatracker.ietf.org/doc/html/draft-ietf-teas-yang-te-30, preference is defined only for primary and secondary paths (using the path-forward-properties grouping) and no longer defined for reverse secondary paths

However, it is not clear whether it is correct to remove the preference for secondary reverse paths at least when the reverse paths are independently routed (i.e., not required to be co-routed) from the primary paths

**Comment by italobusi** [comment]
Tarek has raised concerns that the comment is reversing a previous decision

- [ ] @italobusi : check the old discussion

**Comment by tsaad-dev** [comment]
@italobusi : produce a figure for preference for secondary-reverse-path

**Comment by italobusi** [comment]
> bring back preference to secondary-reverse and add when does preference kick in between multiple paths. Specifically, when multiple paths protect against the same failure (for secondary paths).

See: https://github.com/tsaad-dev/te/issues/56#issuecomment-1453791881

**Comment by italobusi** [comment]
> @italobusi : produce a figure for preference for secondary-reverse-path

Done in https://github.com/tsaad-dev/te/issues/56#issuecomment-1461721423

**Comment by tsaad-dev** [comment]
Addressed in 902c1ad
