### ISSUE TITLE
A question about the design of TE TOPOLOGY objects' identifier

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#194]
Different identifiers for networks, nodes, links and termination points in network topology and TE topology models

For example:
- node-id is an URI
- te-node-id is a dotted-quad

Proposal: update the TE types to be an union with URI; for example: te-node-id is an union between dotted-quad and URI

See: https://mailarchive.ietf.org/arch/msg/teas/SdQbL_yOavuqQxSJqOvJK_d7qTg/

**Comment by italobusi** [comment]
**2023-02-24 TE Call**

Xufeng: the union might not work because the URI can be anything, including a dotted-quad

Better to have two separated fields (as in the TE topology model):

OLD
```
     |     +--rw source?                         te-types:te-node-id
     |     +--rw destination?                    te-types:te-node-id
```

NEW
```
     |     +--rw source?                         te-types:te-node-id
     |     +--rw destination?                    te-types:te-node-id
     |     +--rw source-node-id?                 <<uri>>
     |     +--rw destination-node-id?            <<uri>>
```

- [ ] @tsaad-dev : what do you think?

**Comment by italobusi** [comment]
**2023-03-10 TE Call**

NEW

```
     |     +--rw source
     |     |    +--rw te-node-id?            te-types:te-node-id
     |     |    +--rw node-id?                 <<uri>>
     |     |    +--rw tunnel-tp-id?          binary
     |     +--rw destination
     |     |    +--rw node-id?                 te-types:te-node-id
     |     |    +--rw node-id?                 <<uri>>
     |     |    +--rw tunnel-tp-id?          binary

```

**Comment by tsaad-dev** [comment]
The 'te-node-id' is enough to locate the node in the topology.
However, the TE topology has both (node-id is key).

**Comment by italobusi** [comment]
**2023-05-26 TE Call**

- [ ] **Italo/Aihua**: provide proposed changes to the YANG to address this issue
