### ISSUE TITLE
Tunnel action types in RFC8776-update

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#198]
RFC8776-update defines the YANG base identity for defining tunnel actions but no standard tunnel actions.

In the previous version, the following standard tunnel actions were defined (taken from ietf-te):
- tunnel-action-resetup
- tunnel-action-reoptimize
- tunnel-action-switchpath

Why have them been removed?

Should some of them be brought back to RFC8776-update?

**Comment by tsaad-dev** [comment]
leaf action-type {
              type identityref {
                base te-types:tunnel-actions-type;
              }

Only base is defined in TE-TYPES. Implementations are expected to added identities derived from base.
@italobusi: clarify this in the text.

**Comment by italobusi** [comment]
For further discussion, since it seems that I have got confused by similar names (`tunnel-action-type` and `tunnel-actions-type` )

In RFC8776 we have a `tunnel-action-type` base identity with its derived identities and in RFC8776-bis we have added a new `tunnel-actions-type` with no derived identities

However, in TE tunnel model we have a reference to a derived identity:

https://github.com/tsaad-dev/te/blob/9717721bc28b6f7e6defa110e176aabc94300ec1/ietf-te.yang#L1418-L1437

I am not able to find the `tunnel-action-reoptimize` identity in ietf-te but there is a `tunnel-action-reoptimize` identify defined in RFC8776(-bis) whose base is `tunnel-action-type` and not the new `tunnel-actions-type`

**Comment by italobusi** [comment]
Remove `tunnel-actions-type` from te-types

Update ietf-te:
- replace 'te-types:te-types:tunnel-actions-type' with 'te-types:te-types:tunnel-action-type'
- replace 'te:tunnel-action-reoptimize' with 'te-types:tunnel-action-reoptimize'

**Comment by italobusi** [comment]
> Remove `tunnel-actions-type` from te-types

Done in PR #205

**Comment by tsaad-dev** [comment]
[] Update ietf-te:

replace 'te-types:te-types:tunnel-actions-type' with 'te-types:te-types:tunnel-action-type'
replace 'te:tunnel-action-reoptimize' with 'te-types:tunnel-action-reoptimize'
Addressed in 902c1ad
