### ISSUE TITLE
Describe tunnel-admin-auto in RFC8776-update

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#200]
How to describe the tunnel-admin-auto, which is defined in this document as derived from tunnel-admin-status-type base identity?

**Comment by italobusi** [comment]
As outlined in the new text proposed in PR #205 there is no description for the tunnel-admin-status-type base YANG identity has been provided in RFC8776.

Two options:
1. provide a description of the `tunnel-admin-status-type` base YANG identity and its derived identities, including the `tunnel-admin-auto`, in RFC8776-bis
2. do not provide any description for the `tunnel-admin-auto` identity in RFC8776-bis

My preference is for option 2

**Comment by tsaad-dev** [comment]
Agreement to go with option 2.
