### ISSUE TITLE
What to do with ietf-te-packet-types

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#206]
Following the approach of RFC9314, it is possible to include within the RFC8776-bis a revision of the ietf-te-packet-types that only updates the reference to RFC8776-bis with no other changes: see PR #205 

However, there are further updates in progress for ietf-te-packet-types in:

[draft-ietf-teas-yang-l3-te-topo-13#section-6.2](https://datatracker.ietf.org/doc/html/draft-ietf-teas-yang-l3-te-topo-13#section-6.2)

Are these changes mature to be published within RFC8776-bis or should we plan for an RFC8776-ter where moving these changes (and to be published together with draft-ietf-teas-yang-l3-te-topo)?

**Comment by tsaad-dev** [comment]
Agreement is to pull the new packet types from l3-te-topo into the RFC8776-bis
