### ISSUE TITLE
TE top-level container

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#211]
I am not sure the requirement to enable TE on a system-level is technology and device independent. At least, for Optical domain controllers TE shall always be enabled.

```
  container te {
    presence "Enable TE feature.";
``` 

Maybe an enable leaf with no default would better fit the purpose: not yet sure if this leaf should be defined in the ietf-te (as device independent) or in the ietf-te-device (as device-specific).

See comment 14) in https://mailarchive.ietf.org/arch/msg/teas/26vHESr_cYIsUes6Fuvw3YAOtjk/

**Comment by italobusi** [comment]
I am not sure whether it is worthwhile specifying the default 'false':

```
    leaf enable {
      type boolean;
      default "false";
      description
        "Enables the TE component features.";
    }
```

I think that at least Optical domain controllers should have this leaf set to true by default and it could not be turned off.

**Comment by tsaad-dev** [comment]
Agreement to remove default

**Comment by tsaad-dev** [comment]
Addressed in 902c1ad

**Comment by italobusi** [comment]
https://github.com/tsaad-dev/te/commit/902c1ad8cfbd32ed763f4b6a0a385d2ea44a1b83#r104270906

**Comment by tsaad-dev** [comment]
- Reverted back default under container 'hierarchical-link'
- removed default under container 'te'
