### ISSUE TITLE
Review path-computation-error-reason derived identities

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#215]
I am not sure it makes sense to move the identity tunnel-actions-type so I have kept it within the ietf-te YANG module (for further discussion)

_Originally posted by @italobusi in https://github.com/tsaad-dev/te/issues/184#issuecomment-1168450476_

I was also not sure whether there are some identities to remove

An initial proposal to review one by one was prepared but not yet reviewed: [identities-00.xlsx](https://github.com/tsaad-dev/te/files/10931630/identities-00.xlsx)

**Comment by italobusi** [comment]
I have reviewed the proposal and updated it based on recent discussions: [identities-01.xlsx](https://github.com/tsaad-dev/te/files/10931634/identities-01.xlsx)

**Comment by italobusi** [comment]
After the discussion on 2023-03-10 TE Call, the only identities which requires further discussion are the ones derived from path-computation-error-reason

See updated version of [identities-02.xlsx](https://github.com/tsaad-dev/te/files/10946024/identities-02.xlsx)

**Comment by tsaad-dev** [comment]
Stick to IANA error identities. We can remove 'path-computation-error-no-server' since it is redundant.

**Comment by italobusi** [comment]
If the intention is to stick to IANA error identities, should we do this using an IANA maintained YANG module?

Should this be an identity (extensible by other modules) or an enumeration (extensible only through IANA action)?

**Comment by italobusi** [comment]
2023-06-23

Clarified that the agreement is to:
- remove the `path-computation-error-no-server` identity (redundant)
- keep all the other identities as currently defined
