### ISSUE TITLE
Appendix A. Changes from RFC 8776

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#220]
Provide text for this appendix

**Comment by tsaad-dev** [comment]
what text needs to be added? Diff is not needed since it can be generated at anytime

**Comment by tsaad-dev** [comment]
May not be needed altogether. Please reconsider

**Comment by italobusi** [comment]
2023-06-23

Editorial work: to be done either before or after WG LC (in other words, resolution of this issue is not going to delay/block WG LC)

**Comment by italobusi** [comment]
Requested by Tom Petch: https://mailarchive.ietf.org/arch/msg/teas/pCHwny4a-cUQlcyotgh9Rrtg_TY/

**Comment by boucadair** [comment]
@italobusi, I added an issue for myself right after your prez in teas (and that you didn't find any mention in the 8407bis). Please see my conclusion at: https://github.com/boucadair/rfc8407bis/issues/21.

You will need to add a subsection/appendix with the list of changes :-)
