### ISSUE TITLE
Add an index in path computation

### ISSUE THREAD

**Issue by EstherLerouzic** [tsaad-dev/te#226]
Since there is no index in the requests in the path computation model (only request-id which is not meant to be an index), an API sends the requests in arbitrary order to the path computation server. However in my case, order matters : the result is not the same if you change the order of the requests. For example, because of remaining bandwidth, one order may be feasible for one request and not feasible if the order changes.
I think that adding an index in the request would perfectly solve my issue. 
Do you think it could be possible ?

**Comment by tsaad-dev** [comment]
Discussed the path computation request list:
1. can be order by the user. However, this will dictate order by user all the time
2. add a priority per request, and computation server can visit the list by priority.

Option #2 is what was agreed on.

**Comment by tsaad-dev** [comment]
Path-Computation Model will add new leaf priority.

Request-List
   Request1 -> path<1>-tunnel=FOO
     priority=HI
   Request2 ->path<1>-tunnel=BAR
     priority=LOW
