### ISSUE TITLE
RFC2702 downref

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#239]
Investigate whether it is possible to move the reference to RFC2702 to Informative instead of Normative

**Comment by sergiobelotti** [comment]
@italobusi : we have a similar problem in RFC9093-bis https://github.com/ietf-ccamp-wg/ietf-ccamp-layer0-types-ext-RFC9093-bis/issues/64

**Comment by italobusi** [comment]
Maybe we can remove this reference completely: depending on the resolution of #245

**Comment by italobusi** [comment]
Reference removed while addressing #245 

This issue can be closed together with #245 when PR #247 is merged
