### ISSUE TITLE
Add lsp-restoration identity(ies) to RFC8776-bis

### ISSUE THREAD

**Issue by ju7ien** [tsaad-dev/te#243]
So far, tunnel models don't include any actual way to point to "full LSP rerouting" as a restoration-scheme, i.e. without any pre-X option. We need to be able to specify that an LSP can be restored without any preinstalled state before failure (cf. RFC 4872).

**Comment by italobusi** [comment]
See WG LC comment in https://mailarchive.ietf.org/arch/msg/teas/6AhyY7_rReueG12ZQylIOgpDJ9w/

**Comment by italobusi** [comment]
See proposed resolution in https://datatracker.ietf.org/meeting/118/materials/slides-118-teas-sessa-04-common-yang-data-types-for-traffic-engineering-01.pdf

**Comment by italobusi** [comment]
@tsaad-dev : in [draft-ietf-teas-yang-te-35](https://datatracker.ietf.org/doc/html/draft-ietf-teas-yang-te-35) the default value for the restoration-type has been removed but the default value for the restoration-sheme has not been removed

**Comment by italobusi** [comment]
Closed with https://github.com/tsaad-dev/te/commit/58a7811ae9e4a31190cdfa8603d814608a2f6462
