### ISSUE TITLE
Change name of container explicit-route-objects-always to explicit-route-objects

### ISSUE THREAD

**Issue by tsaad-dev** [tsaad-dev/te#254]
-    container explicit-route-objects-always {
+    container explicit-route-objects {
       description
-        "Container for the 'exclude route' object list.";
+        "Container for the explicit route object lists.";
       list route-object-exclude-always {
         key "index";
         ordered-by user;

**Comment by italobusi** [comment]
Proposed change, including NBC considerations, shared on TEAS WG mailing list:

https://mailarchive.ietf.org/arch/msg/teas/cmf7KsRBxFQZ6oaf-mzWTdZxAYQ/

No feedbacks from the TEAS WG
