### ISSUE TITLE
explicit-route-object (in named constraints and under the tunnel)

### ISSUE THREAD

**Issue by tsaad-dev** [tsaad-dev/te#31]
Currently one can specify the list under the path or leafref the global named constraint
Can look into constricting either/or?
Implementation may pick the one under the tunnel

**Comment by ietf-mpls-yang** [comment]
Explanation:
Constraints explicitly under the tunnel override the ones in the named constraints.

**Comment by ietf-mpls-yang** [comment]
AI (Tarek): describe the behavior in the model

**Comment by ietf-mpls-yang** [comment]
Add text in:
 - description of leafs/grouping
 - in the draft text
 - in the Tutorial document

**Comment by tsaad-dev** [comment]
Addressed in YANG, but to be updated in the tutorial document.
