### ISSUE TITLE
Missing local-protection

### ISSUE THREAD

**Issue by sergiobelotti** [tsaad-dev/te#36]
"local protection" refers to the L bit of the LSPA object defined in RFC5440.

" L flag: Corresponds to the "Local Protection Desired" bit
([RFC3209]) of the SESSION-ATTRIBUTE Object. When set, this
means that the computed path must include links protected with
Fast Reroute as defined in [RFC4090]."

So this is different from asking for a protected path within the domain, as we'll have just one path formed only by protected links (note that in RFC5440 an explicit reference is done to the Fast Reroute, but the meaning of this attribute could be extended to additional technologies using line protected links
see https://github.com/rvilalta/ietf-te-path-computation/issues/24

**Comment by ietf-mpls-yang** [comment]
This is already defined in leaf local-protection-desired (see below):
    ¦+--rw tunnels
    ¦|  +--rw tunnel* [name]
    ¦|  |  +--rw name                                         string
    ¦|  |  +--rw identifier?                                  uint16
    ¦|  |  +--rw description?                                 string
    ¦|  |  +--rw encoding?                                    identityref
    ¦|  |  +--rw switching-type?                              identityref
    ¦|  |  +--rw provisioning-state?                          identityref

<snip>

    ¦|  |  +--rw rsvp-te:lsp-contiguous?                      boolean
    ¦|  |  +--rw rsvp-te:lsp-stitching-desired?               boolean
    ¦|  |  +--rw rsvp-te:lsp-preplanned?                      boolean
    ¦|  |  +--rw rsvp-te:lsp-oob-mapping?                     boolean
    ¦|  |  +--rw rsvp-te:retry-timer?                         uint16
    ¦|  |  +--rw rsvp-te-mpls:local-protection-desired?       empty

**Comment by sergiobelotti** [comment]
I do not think defining local-protection-desidered in rspp-te module is correct, we should be mor general, independently of the way of provisioning.
Said that, we can decide if it is only an "mpls" feature or it owuld be better put the leaf in tunnel part. In the view of separation into 2 drafts this is important to know.

**Comment by ietf-mpls-yang** [comment]
Currently, the model allows for such LSP attributes to be  applied on the headend using the RSVP-TE module as the assumption is they will be signalled via RSVP.

A usecase may be that a higher order controller would want to use an abstracted level of attributes (hide the fact that such attributes are signalled with RSVP).

**Comment by ietf-mpls-yang** [comment]
|  |  |     |  |     +--ro rsvp-te-mpls:state
     |  |  |     |  |     |  +--ro rsvp-te-mpls:local-protection-desired?       empty
     |  |  |     |  |     |  +--ro rsvp-te-mpls:bandwidth-protection-desired?   empty
     |  |  |     |  |     |  +--ro rsvp-te-mpls:node-protection-desired?        empty
     |  |  |     |  |     |  +--ro rsvp-te-mpls:non-php-desired?                empty
     |  |  |     |  |     |  +--ro rsvp-te-mpls:entropy-label-cap?              empty
     |  |  |     |  |     |  +--ro rsvp-te-mpls:oam-mep-entities-desired?       empty
     |  |  |     |  |     |  +--ro rsvp-te-mpls:oam-mip-entities-desired?       empty

Move the above to te-mpls (as opposed to rsvp-te-mpls).

**Comment by ietf-mpls-yang** [comment]
No update

**Comment by italobusi** [comment]
@ietf-mpls-yang : I have seen the following code added to te-types:

https://github.com/ietf-mpls-yang/te/blob/cbd793c8ba57c5faa492f12c7916aa3c02e0f4fc/ietf-te-types.yang#L1982-L1991

Is this intended to resolve this issue?

If this is the case, I think that the description needs to be slightly updated

What about something like:

> Link Protection Type desired for the links included in the computed path

@efralaz : what do you think?

**Comment by ietf-mpls-yang** [comment]
Look into constraints if can request computed path to pick link protection type

**Comment by italobusi** [comment]
@tsaad-dev , @efralaz : is this issue still open or can we close it?

**Comment by italobusi** [comment]
The comment has been resolved:

https://tools.ietf.org/html/draft-ietf-teas-yang-te-types-08

@tsaad-dev : could you please close this issue?
