### ISSUE TITLE
MEP/MIP OAM on the tunnel

### ISSUE THREAD

**Issue by tsaad-dev** [tsaad-dev/te#40]
AI (Italo): please look into what more is needed for OAM on the tunnel. 
     |  |  |     |  |     |  +--ro rsvp-te-mpls:oam-mep-entities-desired?       empty
     |  |  |     |  |     |  +--ro rsvp-te-mpls:oam-mip-entities-desired?       empty

**Comment by ietf-mpls-yang** [comment]
This ideally will be addressed in an OAM model augmentation to TE model. Agreement is to remove from RSVP-TE for now.

**Comment by tsaad-dev** [comment]
Removed.
