### ISSUE TITLE
Delete preference for the tunnel

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#45]
Need to remove the `preference ` leaf from the tunnel: the preference leafe on the path is sufficient for the objective stated in https://github.com/tsaad-dev/te/issues/16#issuecomment-360816650:

> The preference defines a priority to visit a path in the list

**Comment by italobusi** [comment]
Code to remove:

```
    leaf preference {
      type uint8 {
        range "1..255";
      }
      default 100;
      description
        "Specifies a preference for this tunnel.
         A lower number signifies a better preference";
    }

```

**Comment by tsaad-dev** [comment]
Addressed

**Comment by tsaad-dev** [comment]
c644b08
