### ISSUE TITLE
Expand on description of named-constraints

### ISSUE THREAD

**Issue by tsaad-dev** [tsaad-dev/te#46]
Expand on description of named-constraints

**Comment by tsaad-dev** [comment]
@italobusi please review current descriptions. If OK, we want to close this.

**Comment by sergiobelotti** [comment]
Looking at the definition of named-path-constraints I see the attempt to associate a set of constraints with a name , in the key name definition.
I would expect some further description in the text (maybe non only in YANG) explaining the meaning and usage (why is useful to have this "named" concept). Maybe this concept of named is trivial in packet world but not the same in optical.

**Comment by italobusi** [comment]
**2020-09-25 TEAS Call**
The named-path-constraints are useful when multiple tunnels have the same set of path constraints to avoid specifying the same set of path constraints on multiple tunnels (the fact that this situation today is quite uncommon in OTN but quite common in packet networks is outside the scope of this draft). In case of a conflict between a path constraint specified in the tunnel and a path constraint specified in the referenced named-path-constraints, the path constraint specified in the tunnel takes precedence.

@tsaad-dev : It would be worthwhile adding some text clarifying this behavior.

**Comment by tsaad-dev** [comment]
Please review the below proposed changes to section 5.1.1. of the I-D if addresses this issue.

5.1.1.  TE Globals

   The 'globals' container covers properties that control TE features
   behavior system-wide, and its respective state (see Figure 3).  The
   TE globals configuration include:

   named-admin-groups:

    ¦ A container for the list of named (extended) administrative groups
    ¦ that may be applied to TE links.

   named-srlgs:

    ¦ A container for the list named Shared Risk Link Groups (SRLGs)
    ¦ that may be applied to TE links.

   named-path-constraints:

    ¦ A container for a list of named path constraints.  Each named
    ¦ constraint is composed of a set of constraints that can be applied
    ¦ during path computation.  A named path constraint can be applied
    ¦ to TE tunnels.  Path constraints may also be specified directly
    ¦ under the TE tunnel.  The path constraint specified under the TE
    ¦ tunnel take precedence when there is a conflict between
    ¦ constraints derived from a referenced named-path-constraint set,
    ¦ and constraints specified under the TE tunnel.

**Comment by tsaad-net** [comment]
typo:
s/Each named path constraint
s/The path constraint specified/The path constraints specified

Path constraints may also be specified directly
¦ under the TE tunnel.  The path constraints specified under the TE
¦ tunnel take precedence over
¦ constraints derived from a referenced named path constraint.

**Comment by italobusi** [comment]
Closed with https://github.com/tsaad-dev/drafts/issues/5
