### ISSUE TITLE
Difference between signaling-type and path-setup-protocol

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#49]
It seems that the protocol used to setup a path in ietf-te-types is called signaling-type while in ietf-te is called path-setup-protocol. Also the default values are different (RSVP in ietf-te-types and static in ietf-te)

This is the definition in ietf-te-types:

```
  grouping common-constraints {
    <...>
    leaf signaling-type {
      type identityref {
        base path-signaling-type;
      }
      default te-types:path-setup-rsvp;
      description "TE tunnel path signaling type";
    }

```

These are the definitions in ietf-te:

```
  grouping p2p-path-properties-common {
    description
      "TE tunnel common path properties configuration grouping";
    leaf name {
      type string;
      description "TE path name";
    }
    leaf path-setup-protocol {
      type identityref {
        base te-types:path-signaling-type;
      }
      default te-types:path-setup-static;
      description
        "Signaling protocol used to set up this tunnel";
    }

```

Note that this leaf duplicates with the signaling-type leaf from imported te-types:common-constraints

```
  grouping p2p-path-candidate-secondary-path-config {
    description
      "Configuration parameters relating to a secondary path which
      is a candidate for a particular primary path";

    leaf secondary-path {
      type leafref {
        path "../../../../../p2p-secondary-paths/" +
             "p2p-secondary-path/name";
      }
      description
        "A reference to the secondary path that should be utilised
        when the containing primary path option is in use";
    }

    leaf path-setup-protocol {
      type identityref {
        base te-types:path-signaling-type;
      }
      default te-types:path-setup-static;
      description
        "Signaling protocol used to set up this tunnel";
    }
  }

```

Note that this leaf duplicates with the both the path-setup-protocol leaf and the signaling-type leaf, from imported te-types:common-constraints, within the p2p-secondary-path etnry

```
  grouping p2p-secondary-reverse-path-properties {
    description
      "Configuration parameters relating to a secondary path which
       is a candidate for a particular primary path";

    leaf secondary-path {
      type leafref {
        path "../../../../../p2p-secondary-paths/" +
             "p2p-secondary-path/name";
      }
      description
        "A reference to the secondary path that should be utilised
        when the containing primary path option is in use";
    }

    leaf path-setup-protocol {
      type identityref {
        base te-types:path-signaling-type;
      }
      default te-types:path-setup-static;
      description
        "Signaling protocol used to set up this tunnel";
    }
  }

```

Note that this leaf duplicates with the both the path-setup-protocol leaf and the signaling-type leaf, from imported te-types:common-constraints, within the p2p-secondary-path etnry

```
  grouping lsp-properties-state {
    <...>
    leaf path-setup-protocol {
      type identityref {
        base te-types:path-signaling-type;
      }
      default te-types:path-setup-static;
      description
        "Signaling protocol used to set up this tunnel";
    }

```

**Comment by italobusi** [comment]
It is proposed to remove all the occurrences of the path-setup-protocol leaves within the ietf-te which are duplicated.

The path-setup-protocol would remain only within the lsp-properties-state grouping:

- it is worthwhile aligning the name with the ietf-te-types;

- there is no need to define any default since this is not a configurable leaf

- this information refers to the LSP and not to the tunnel

Proposed update:

```
  grouping lsp-properties-state {
    <...>
    leaf signaling-type {
      type identityref {
        base te-types:path-signaling-type;
      }
      description
        "Signaling protocol used to set up this LSP";
    }

```

**Comment by tsaad-dev** [comment]
The one under the path "path-setup-protocol" is used to indicate the desired setup protocol for this path (this can be primary or secondary).

The one under the LSP is for the state (i.e. when you check any LSP what was used to signal it)

**Comment by italobusi** [comment]
> The one under the path "path-setup-protocol" is used to indicate the desired setup protocol for this path (this can be primary or secondary).
> 

@tsaad-dev : I agree. This information is already defined in `te-types` and the attribute is called `signaling-type`. The https://github.com/tsaad-dev/te/commit/b06caf734a382f63fbbc235a55e84f687f3e4b6b has fixed this issue.

> The one under the LSP is for the state (i.e. when you check any LSP what was used to signal it)

@tsaad-dev : I agree. The doubts here are:
- do we need a different name rather than re-using the same name?
- do we need a default value for the state?
- the description is not correct

**Comment by tsaad-dev** [comment]
Change path-setup-protocol -> signaling-type
