### ISSUE TITLE
Tunnel: new attribute for dependency Tunnel

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#53]
As discussed in the context of open issue #48 

> To avoid the inappropriate usage of "provisioning-state" attribute we need to define a new attribute , as reported above, to indicate that a tunnel has a "dependency-tunnel" scope and that, the client could decide do not delete it even in case no other client tunnel is using it. If this attribute is setup it should avoid that automatically the tunnel would deleted when no client traffic is using the server tunnel.

**Comment by italobusi** [comment]
**2020-02-21 Call**

Agreed to:
- change the name of provisioning-state to admin-state
- create a new identity for tunnel-admin-state with three values: up, down and auto-up

**Comment by tsaad-dev** [comment]
description for auto-up:
"The admin-status transitions to up once it is used by the client layer."
default: "UP"

**Comment by tsaad-dev** [comment]
ADMIN-UP
ADMIN-DOWN
ADMIN-AUTO

"The status transitions to "ADMIN-UP" when the tunnel used by the client layer, and to "ADMIN-DOWN" when it is not used by the client layer."
