### ISSUE TITLE
How to report path properties in case path computation fails

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#54]
There are use cases (e.g., optical parameters) where path properties deserve to be returned to the requester in case of no-path, so that it can be aware of the blocking item and adapt furthers requests; a possible way to address that could be to:
- include a branch "path-properties" under the "no-path" to convey some optional properties,
- add a "blocking reason" under "no-path", in the spirit of the PCEP's NO-PATH-VECTOR (https://www.iana.org/assignments/pcep/pcep.xhtml#no-path-vector-tlv);

See https://github.com/rvilalta/ietf-te-path-computation/issues/63

**Comment by tsaad-dev** [comment]
Review path-computation-error-reason identities.
- pre computation checks are only possible.
- AI [Italo/Sergio]: need to add unknown source/destination/inclusion-hop
we have path-computation-error-no-server,
do we need  path-computation-error-no-child-server?

**Comment by sergiobelotti** [comment]
We provided a proposal.
Items for further discussion:

1) Need for different identities corresponding to codes 31 (), 28 () and 21 ()
We have proposed not to distinguish between 28 and 21, not to expose the underlying PCE architecture but to distinguish local server failures (local PCE) from dependent server failures (child PCE or BRPC downstream PCE)
2) Flag 27 (PKS expansion failure) looks applicable to path setup and not to path computation
3) Flags 26 (No GCO migration path found) and 25 (No GCO solution found) are related to GCO and out of scope
4) Flag 24 (P2MP Reachability Problem) is related to p2mp. Out of scope from the I-D?
5) Flag 23 (No RWA constraints met) is WSON specific and should be defined in WSON Tunnel
6) Flags 22 (Destination domain unknown); 20 (No available resource in one or more domains) and 19 (Destination is not found in the indicated domain) are H-PCE specific and not applicable to the te YANG model
7) Flag 18 (Protection Mismatch) is not clear to us and requires further discussion/investigation
8) Flag 17 (No Resource): the difference with the no-path case is not clear
9) Flag 16 (Granularity not supported): we propose to add it
10) Flag 15 (No endpoint label resource) is covered by the path-computation-error-no-inclusion-hop
11) Flag 14 (No endpoint label resource in range): it is not clear how to distinguish between the label sets of path-in-segment and path-out-segment
12) Flag 13 (No label resource in range): it is not clear which label set it is referred to
13) Flag 12 (LOAD-BALANCING could not be performed with thebandwidth constraints): it is not fully described in PCE I-D but it seems packet technology-specific

**Comment by sergiobelotti** [comment]
> Review path-computation-error-reason identities.
> 
> * pre computation checks are only possible.
> * AI [Italo/Sergio]: need to add unknown source/destination/inclusion-hop
>   we have path-computation-error-no-server,
>   do we need  path-computation-error-no-child-server?

Moreover about
-pre computation checks are only possible

RFC 5440  https://www.iana.org/go/rfc5440 
 in the NO-PATH object , C flag, when set, indicates the set of unsatisfied constraints (reason why a path could not be found) in the PC Report message. including the relevant PCEP objects.  This seems in line with the request to provide reasonf for failed path comutation and not just a pre-computation checks.
-

**Comment by italobusi** [comment]
> We provided a proposal.
> Items for further discussion:
> 
> 1. Need for different identities corresponding to codes 31 (), 28 () and 21 ()
>    We have proposed not to distinguish between 28 and 21, not to expose the underlying PCE architecture but to distinguish local server failures (local PCE) from dependent server failures (child PCE or BRPC downstream PCE)
> 2. Flag 27 (PKS expansion failure) looks applicable to path setup and not to path computation
> 3. Flags 26 (No GCO migration path found) and 25 (No GCO solution found) are related to GCO and out of scope
> 4. Flag 24 (P2MP Reachability Problem) is related to p2mp. Out of scope from the I-D?
> 5. Flag 23 (No RWA constraints met) is WSON specific and should be defined in WSON Tunnel
> 6. Flags 22 (Destination domain unknown); 20 (No available resource in one or more domains) and 19 (Destination is not found in the indicated domain) are H-PCE specific and not applicable to the te YANG model
> 7. Flag 18 (Protection Mismatch) is not clear to us and requires further discussion/investigation
> 8. Flag 17 (No Resource): the difference with the no-path case is not clear
> 9. Flag 16 (Granularity not supported): we propose to add it
> 10. Flag 15 (No endpoint label resource) is covered by the path-computation-error-no-inclusion-hop
> 11. Flag 14 (No endpoint label resource in range): it is not clear how to distinguish between the label sets of path-in-segment and path-out-segment
> 12. Flag 13 (No label resource in range): it is not clear which label set it is referred to
> 13. Flag 12 (LOAD-BALANCING could not be performed with thebandwidth constraints): it is not fully described in PCE I-D but it seems packet technology-specific

See pull request #62

**Comment by tsaad-dev** [comment]
AI: Sergio to go over the list above and identify any missing new identities that we need to add to the model.

**Comment by sergiobelotti** [comment]
RFC 5440 NO-PATH-VECTOR TLV Flag correspondence in the model:
codes 31 () --> identity path-computation-error-no-server 
codes 28 () and 21 () --> identity path-computation-error-no-dependent-server


code 16 (Granularity not supported) --> identity path-computation-error-hop-granularity-not-supported
code 15 (No endpoint label resource)-->identity path-computation-error-no-inclusion-hop 

to be discussed as possible further update :
codes 26 (No GCO migration path found) and 25 (No GCO solution found) are related to Global concurrent optimization. GCO . If Path computation server support this type of optimization  two new identities would be needed to add.  

Remain open these points below since not clear form the origin PCEP description:
code 12 (LOAD-BALANCING could not be performed with the bandwidth constraints): it is not fully described in PCE I-D but it seems packet technology-specific
code 18 (Protection Mismatch) is not clear to us and requires further discussion/investigation

**Comment by tsaad-dev** [comment]
Added all PC errors see commits 32322b8  and eb3f320
