### ISSUE TITLE
Metric accumulative attribute type

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#55]
metric's accumulative-value is currently defined as a "uint64 whereas it doesn't fit optical metrics at all, a decimal variation would be far more appropriate;

See: https://github.com/rvilalta/ietf-te-path-computation/issues/64

**Comment by tsaad-dev** [comment]
Agreement:
- new augmentation (via new optical module) for optical path attributes
- new list for metric types that do not fit in uint64 bits
- may do leaf_type leaf_value for different attributes types

**Comment by tsaad-dev** [comment]
closed as per above!
