### ISSUE TITLE
association-type new identity for diversity

### ISSUE THREAD

**Issue by sergiobelotti** [tsaad-dev/te#57]
in some scenarios like  #52 for Y.cable, it is needed to have the possibility to "associate" tunnels for diversity. In te-types it seems as though no type for diversity is defined .

**Comment by tsaad-dev** [comment]
AIs:
- Add new association type identity in the TE Yang module.
- Add new association object at the path level.

**Comment by tsaad-dev** [comment]
AI:
Italo to add description in tutorial for describing how association works between between tunnels and paths.

**Comment by tsaad-dev** [comment]
A        B          C
10       10         
         11         11
         
         

A-P1        B-P2          C-P1
10          10         
            11            11

Question?
A-P1-foo         A-P2-bar
10               10

if you want diverse with different paths of **same** tunnel, you have to configure the disjoint knob

**Comment by tsaad-dev** [comment]
Enhance description under association and disjoint knob.
