### ISSUE TITLE
source definition of the association-objects container 

### ISSUE THREAD

**Issue by sergiobelotti** [tsaad-dev/te#58]
In the tunnel model is defined association-object to be used for tunnel association.
The definition is following what defined for ASSOCIATION object in RFC 4872, indicating the source field as an "An IPv4 or IPv6 address, respectively, that is associated to the node that originated the association.". 
But in our Yang model the field is defined as te-node-id 
leaf source {
          type te-types:te-node-id;
          description "Association source";
          reference "RFC4872";
        }

**Comment by tsaad-dev** [comment]
Add a choice of IP/TE node ID

Update the description:
"The TE node ID or IP address of the node that originated the association."

**Comment by tsaad-dev** [comment]
see latest commit
