### ISSUE TITLE
Add p2mp tunnnel details in draft-ietf-teas-yang-te

### ISSUE THREAD

**Issue by oscargdd** [tsaad-dev/te#70]
Currently the has to main lists under the tunnels grouping, tunnel (which refers to p2p ) and tunnel-p2mp. So far, what is available for p2mp is simply a name, identifier, description and operational-state.
 
|  +--rw tunnel-p2mp* [name]
     |     +--rw name                 string
     |     +--rw identifier?          uint16
     |     +--rw description?         string
     |     +--ro operational-state?   identityref

The p2mp list needs to be completed in a similar way as the p2p tunnel one.

**Comment by tsaad-dev** [comment]
We concluded that p2mp tunnels can be addressed in a separate document and module.
Removed references to p2mp in c595597
