### ISSUE TITLE
Add RPC for TE tunnel

### ISSUE THREAD

**Issue by tsaad-dev** [tsaad-dev/te#73]

**Comment by tsaad-dev** [comment]
RPC REOPT on TE tunnels with parameters
 INPUT:
 tunnel: name or all
 REOPT CONDITIONs:
   - cond1 = disruptive/non-disruptive

RPC RESETUP on TE tunnels with parameters
 INPUT:
 tunnel: name or all
 
OUTPUT:
 OK RPC accepted
 REJECTED

**Comment by tsaad-dev** [comment]
see c644b08

**Comment by italobusi** [comment]
@tsaad-dev (from @italobusi and @sergiobelotti) : for the path-computation RPC we need it to be define as:

```
    +---x tunnels-path-compute
       +---w input
       +--ro output
```

We will then augment both input and output in the path-computation RPC:

```
  augment /te:tunnels-path-compute/te:input:
    +---- path-request* [request-id]
    |  ...................
  augment /te:tunnels-path-compute/te:output:
    +--ro response* [response-id]
       ...................

```
