### ISSUE TITLE
Single use groupings

### ISSUE THREAD

**Issue by tsaad-dev** [tsaad-dev/te#75]
6. There is a number of single-instantiated groupings:
   - p2p-reverse-path-properties
   - p2p-primary-reverse-path-properties
   - p2p-secondary-reverse-path-properties
   - p2p-primary-path-properties
   - p2p-secondary-path-properties
   - hierarchical-link-properties
   - protection-restoration-properties-state
   - ... (mybe the most of all that groupings)
   While it is a good mechanism to allow repeated instantiation of a group of
   statements, it can produce kind of "spaghetti code" - with such a number of
   groupings, it is quite challenging for human readers to follow the schema.
   And one of the YANG advantages is its readability. Please consider, if there
   is some real possibility to reuse groupings somewhere outside the schema
   itself. If yes, then ok - readability is the price for reuseability, but
   otherwise you actually don't get anything for poor readability.

**Comment by tsaad-dev** [comment]
Addressed in latest commit.

**Comment by italobusi** [comment]
@tsaad-dev (from @italobusi and @sergiobelotti): we are checking the path-computation YANG model and some groupings may be needed to be re-used

At least this container would be needed to be re-used by path-computation YANG:

```
     |     +--rw hierarchy
     |     |  +--rw dependency-tunnels
     |     |  |  +--rw dependency-tunnel* [name]
     |     |  |     +--rw name
     |     |  |     |       -> ../../../../../../tunnels/tunnel/name
     |     |  |     +--rw encoding?         identityref
     |     |  |     +--rw switching-type?   identityref
     |     |  +--rw hierarchical-link
     |     |     +--rw local-te-node-id?         te-types:te-node-id
     |     |     +--rw local-te-link-tp-id?      te-types:te-tp-id
     |     |     +--rw remote-te-node-id?        te-types:te-node-id
     |     |     +--rw te-topology-identifier
     |     |        +--rw provider-id?   te-global-id
     |     |        +--rw client-id?     te-global-id
     |     |        +--rw topology-id?   te-topology-id

```

**Comment by italobusi** [comment]
While working on this issue with @sergiobelotti, we have got some doubts: see new open issues #80, #81, #82 and #83

**Comment by italobusi** [comment]
@tsaad-dev : please see pull request #86 

There are other groupings used only once but for us they can stay as they are

**Comment by tsaad-dev** [comment]
Closed with the latest merge.
