### ISSUE TITLE
Path re-setup action

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#79]
https://github.com/tsaad-dev/te/blob/7a901a620de6307f838b8a08a3455af5a8d4ab67/rsvp_te_model.tree#L2968-L2978

It the path re-setup action generic or should it be moved to packet technology-specific modules?

If it is defined as generic, is there a way to remove its support from Optical technology-specific augmentations?

**Comment by italobusi** [comment]
This RPC needs to be re-reconciled with the tunnel-action definition:

https://github.com/tsaad-dev/te/blob/2eb16b5c410134d6e183c1fb39c895166f9f648f/ietf-te.yang#L1071-L1092

1) It seems that using the tunnel-actions-type is preferable than using the te-types:tunnel-action-type identity in both cases

2) do we need to support the (one-tunnel) case in the RPC since the same result can be achieved using the actions?

3) Should we report the action-result also in the RPC output?

4) Editorial: fix the description of the action-result for the tunnel-action. Should be "The result of the Tunnel action"

**Comment by tsaad-dev** [comment]
Update the action to use the new tunnel-actions-type
Move resetup to packet TE module.
Add output to the RPC
Description to change:
OLD:
description "The result of the RPC operation."; 
NEW:
description "The result of the tunnel action operation .";
