### ISSUE TITLE
Constraints on Sharing Resource Tunnels

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#80]
https://github.com/tsaad-dev/te/blob/2eb16b5c410134d6e183c1fb39c895166f9f648f/ietf-te.yang#L1282-L1286

This constraints applies only to secondary paths which are not 1+1 protected and not to any path.

It should also be possible to reference which secondary paths of these tunnel the bandwidth could be shared with. An option to share bandwidth with any secondary path can also be allowed (e.g., if no secondary path is specified)

**Comment by italobusi** [comment]
Also in the LSP state, only secondary LSPs can share bandwidth and it is worthwhile reporting which LSPs are sharing bandwidth:

https://github.com/tsaad-dev/te/blob/2eb16b5c410134d6e183c1fb39c895166f9f648f/ietf-te.yang#L388-L402

**Comment by italobusi** [comment]
**2020-03-13 TEAS call**

It may be useful to share resources between two primary paths of two mutually exclusive tunnels (make-before-break between two tunnels)

May be worthwhile considering a new association type for resource sharing: for further discussion

**Comment by tsaad-dev** [comment]
Agreement to delete grouping shared-resources-tunnels.

**Comment by tsaad-dev** [comment]
We studied the case of using the Association Object for multiple secondary paths of different tunnels. 

AI(Italo): to follow up with detailed example. For now, the agreement was to remove as per this commit.

T1:
  Primary P1
  Secondary S1
    Shared-Group SG1
    LSP:
     Using the shared resource: {T2-LSP ..}

T2 (fault):
  Primary P2
  Secondary S2
   Shared-Group SG1
    LSP:
     Using the shared resource: {T2-LSP ..}

T3:
  Primary P3
  Secondary S3
   Shared-Group SG1, SG2, SG3....
   LSP:
     Using shared resource: {T2-LSP ..}
