### ISSUE TITLE
Preference and k-request-path attributes

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#81]
https://github.com/tsaad-dev/te/blob/2eb16b5c410134d6e183c1fb39c895166f9f648f/ietf-te.yang#L543-L559

These attributes are currently defined only for p2p-primary-path and p2p-secondary-path but not for p2p-primary-reverse-path

However, it seems that these attributes are applicable only to p2p-primary-path and represent the preference of a "path set" (primary path, primary-reverse path, secondary paths and secondary-reverse paths) and the number of computed "path sets" to report

**Comment by tsaad-dev** [comment]
k-requested-paths can be removed from the reverse path.

**Comment by tsaad-dev** [comment]
Tunnel
Primary
 k=2 (rw)
  k=1, path1
  k=2, path2
  Primary-reverse-path
    computed-path-properties (k=2, ro)
      k=1, reverse-path1
      k=2, reverse-path2
    candidate-secondary-reverse-paths

Secondary
 srlg-disjoint
 computed-path-properties (k=2, ro)
  k=1, disjoint-path3
  k=2, disjoint-path2

**Comment by tsaad-dev** [comment]
k-requested-path is only configurable under the primary path

**Comment by italobusi** [comment]
@tsaad-dev : see our proposal in pull request #86

**Comment by tsaad-dev** [comment]
Issue addressed with the latest merge above.
