### ISSUE TITLE
Do we need the path-properties grouping?

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#82]
https://github.com/tsaad-dev/te/blob/2eb16b5c410134d6e183c1fb39c895166f9f648f/ietf-te.yang#L270-L326

This grouping is almost the same as the te-types:generic-path-properties:

1) Do we need to report the bandwidth as an output of path computation?

Note also that the bandwidth leaf is not using the te-bandwidth container structure that allows technology-specific augmentations

2) Do we need to report the disjointness-type as an output of path computation?

It seems that there are no other differences between this grouping and the te-types:generic-path-properties grouping

**Comment by italobusi** [comment]
Also the uses shared-resources-tunnels is different

**Comment by italobusi** [comment]
2020-02-28 TEAS call

The bandwidth and disjointness-type of computed path can be different than the requested one.

The disjointness-type for computed primary-path could be the minimum level of disjointness of all the secondary paths:

```
primary (SRLG) -> min(no-disjoint)
  secondary-1 -> no-disjoint
  secondary-2 -> node
  secondary-3 -> link

```

**Comment by italobusi** [comment]
@tsaad-dev : I think we can now qualify this issue as an enhancement (at least we need to enhance the description)

It may be also worthwhile reusing the te-types:generic-path-properties and just add the missing attributes

I can work together with Sergio and prepare a pull request to address it together with issue #75

If you agree, you can assign this issue to me and/or Sergio

**Comment by italobusi** [comment]
@tsaad-dev : please see pull request #86 

We have proposed to define the path-properties by using the te-types:generic-path-properties and augmenting it with the additional attributes

We have also proposed to replace the bandwidth leaf with the te-types:te-bandwidth containerto allow technology-specific augmentations

**Comment by tsaad-dev** [comment]
closed in the latest merge from Italo/Sergio
