### ISSUE TITLE
Multiple reverse secondary paths?

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#83]
https://github.com/tsaad-dev/te/blob/2eb16b5c410134d6e183c1fb39c895166f9f648f/ietf-te.yang#L523-L533

A p2p-primary-reverse-path should contain a list of zero, one or more p2p-secondary-reverse-paths (same reason as for primary-path)

Why a leafref is used instead of providing all the reverse path information?

**Comment by italobusi** [comment]
**2020-02-28 TEAS call**

Agreement:

```
Primary-List
   Primary-1 (fwd)
      Rev-Primary-2 (rev)
         Rev-Candidate-Secondary-list (rev)
            Secondary-3-ref (rev)
            Secondary-4-ref (rev)
            Secondary-5-ref (rev)
      Candidate-Secondary-list (fwd)
         Secondary-1-ref (fwd)
         Secondary-2-ref (fwd)
    Primary-3 (fwd)
       Candidate-Secondary-list (fwd)
          Secondary-1-ref (fwd)

Secondary-list
   Secondary-1 (fwd)
   Secondary-2 (fwd)
Rev-Secondary-list
   Secondary-3-ref (rev)
   Secondary-4-ref (rev)
   Secondary-5-ref (rev)
```

**Comment by italobusi** [comment]
@tsaad-dev : I think we can now qualify this issue as a bug or as an enhancement

I can work together with Sergio and prepare a pull request to address it together with issue #75 

If you agree, you can assign this issue to me and/or Sergio

**Comment by tsaad-dev** [comment]
Addressed in latest commit
