### ISSUE TITLE
No default for the operational-state

### ISSUE THREAD

**Issue by italobusi** [tsaad-dev/te#89]
https://github.com/tsaad-dev/te/blob/c5809f0fc40fa84620b8319cec5eadb5a223beea/ietf-te.yang#L900

Since the operational-state is config-false, we think that no default should be defined

It is also not fully clear what is the meaning of admin-status-down and operational-status-down.

**Comment by tsaad-dev** [comment]
We need to correct the description
OLD:
description "TE tunnel administrative state.";
NEW:
description "TE tunnel operational state.";
