### ISSUE TITLE
Shared Resource Association definition

### ISSUE THREAD

**Issue by tsaad-dev** [tsaad-dev/te#91]
The shared resource association is overloaded for e2e and for sharing single resource (e.g. MBB) - see https://tools.ietf.org/html/rfc6689#section-2.4 and section 3.

We need to check if model contains enough attributes to distinguish between the two cases.

**Comment by italobusi** [comment]
Maybe also this RFC can be relevant for this discussion:

https://tools.ietf.org/html/rfc8745

**Comment by italobusi** [comment]
2020-04-03 TEAS Call

No need to change the model but to describe how it is used: https://github.com/tsaad-dev/te/issues/93#issuecomment-608526351
