### ISSUE TITLE
Rename: src-tp-id -> src-ttp-id, dst-tp-id -> dst-ttp-id

### ISSUE THREAD

**Issue by haomianzheng** [tsaad-dev/te#94]
This is to re-capture one discussion in https://mailarchive.ietf.org/arch/msg/teas/v_NqH1hJm9mqgyMeQlmcoNUUiaA/ . Basically in the module we use -tp to indicate the LTP, and the TTP should be referred as -ttp.

**Comment by tsaad-dev** [comment]
For consistency with the TE topology model, we will use src-tunnel-tp-id and dst-tunnel-tp-id
