### ISSUE TITLE
Update description of lsps-state container + add sestion to describe it (e.g. 3.4) + question 

### ISSUE THREAD

**Issue by oscargdd** [tsaad-dev/te#98]
The lsps-state container is under te and holds the complete list of LSPs associated to all tunnels (not a particular tunnel ). Current description is 
description "List of LSPs associated with the tunnel.";
Update the description to reflect it.

Also, there is one section per main container (globals, TE, interfaces), so another one on lsps-state would make sense. 

Finally, all the information in that container is a duplicate from the lsps container under the tunnel container. If the intention is to maintain the list of LSPs that have been created in the Network (or device), why not add just a list of references to the leafs in primary and secondary paths?

**Comment by italobusi** [comment]
**2020-05-22 TEAS call**

To allow retrieving the list of LSPs within a given tunnel, we can add an augmentation constrained by a feature:

```
     +--rw tunnels
     |  +--rw tunnel* [name]

     |     +--rw primary-paths
     |     |  +--rw primary-path* [name]
     |     |     +--rw name                             string

     |     |     +--ro lsps
     |     |     |  +--ro lsp* [lsp-id]
     |     |     |  +--leafref

augmentation in the same ietf-te module:
     |     |     |  +--.......              { feature-dependent-lsp-state }

     +--ro lsps-state
     |  +--ro lsp*
     |          [source destination tunnel-id lsp-id extended-tunnel-id]
```

**Comment by italobusi** [comment]
**2020-05-22 TEAS call**

Open issue (from 2020-05-15): how to avoid defining five leafrefs to point to LSP state (source destination tunnel-id lsp-id extended-tunnel-id)

Possible solution:

```
     +--rw tunnels
     |  +--rw tunnel* [name]

     |     +--rw primary-paths
     |     |  +--rw primary-path* [name]
     |     |     +--rw name                             string

     |     |     +--ro lsps
     |     |     |  +--ro source               leafref
     |     |     |  +--ro destination          leafref
     |     |     |  +--ro tunnel-id            leafref
     |     |     |  +--ro extended-tunnel-id   leafref
     |     |     |  +--ro lsp* [lsp-id]
     |     |     |  |  +--ro lsp-id            leafref

augmentation in the same ietf-te module:
     |     |     |  |  +--.......              { feature-dependent-lsp-state }

     +--ro lsps-state
     |  +--ro lsp*
     |          [source destination tunnel-id lsp-id extended-tunnel-id]

```

**Comment by tsaad-dev** [comment]
lsps-state list can be keyed by an index 32-bit number (on controller, unique per LSPs all over the network).

![image](https://user-images.githubusercontent.com/9702603/83279146-aa2bea00-a1a2-11ea-9cd1-1679fee76cee.png)

![image](https://user-images.githubusercontent.com/9702603/83282709-fa597b00-a1a7-11ea-8be3-b63fc071d925.png)
